version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "postgres-socket:/var/run/postgresql"
      - type: bind
        source: ../
        target: /workspace
 
  psql:
    image: postgres:11.9
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=codeany
      - POSTGRES_PASSWORD=pass1234
    network_mode: service:app
    volumes:
      
      - "../db-data:/var/lib/postgresql/data"
      - "postgres-socket:/var/run/postgresql"

volumes:
  postgres-socket: